#!/bin/sh
set -e



remove() {
	# Restore the debian origin if we are going to break up things
	if [ "`readlink /etc/dpkg/origins/default`" = "mclinux" ]; then
		ln -sf debian /etc/dpkg/origins/default
	fi
	
	# Restore os-release
	if [ -e "/etc/os-release.distrib" ]; then
		rm -f "/etc/os-release" # that's our link!
		dpkg-divert --rename --package meta-base-mclinux --divert "/etc/os-release.distrib" --remove "/etc/os-release"
	fi
}

case "$1" in
	"remove")
		remove
		;;
esac
